"""Markdown/PDF 내보내기"""
import io
from datetime import datetime
from pathlib import Path

from fpdf import FPDF

from config import DATA_DIR, CATEGORIES, SENTIMENTS
from utils.helpers import safe_read_json, today_str


# ── 한글 지원 PDF 클래스 ──
class _KoreanPDF(FPDF):
    """한글 폰트를 자동 등록하는 FPDF 서브클래스"""

    _font_registered = False

    def _register_korean_font(self):
        if _KoreanPDF._font_registered:
            return
        # Windows 기본 한글 폰트 (맑은 고딕)
        font_path = Path("C:/Windows/Fonts/malgun.ttf")
        if font_path.exists():
            self.add_font("malgun", "", str(font_path), uni=True)
            bold_path = Path("C:/Windows/Fonts/malgunbd.ttf")
            if bold_path.exists():
                self.add_font("malgun", "B", str(bold_path), uni=True)
            _KoreanPDF._font_registered = True

    def header(self):
        self._register_korean_font()
        self.set_font("malgun", "B", 14)
        self.cell(0, 10, "AI News Radar", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(2)

    def footer(self):
        self.set_y(-15)
        self.set_font("malgun", "", 8)
        self.set_text_color(128)
        self.cell(0, 10, f"Generated by AI News Radar | {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="C")


def _safe_text(text: str) -> str:
    """PDF에 안전한 텍스트로 변환 (제어 문자 제거)"""
    return text.replace("\r", "").replace("\x00", "")


def export_briefing_markdown() -> str:
    """오늘의 브리핑을 Markdown으로 내보내기"""
    briefings = safe_read_json(DATA_DIR / "briefings.json", [])
    today = today_str()
    briefing = next((b for b in briefings if b.get("date") == today), None)

    if not briefing:
        return "# 오늘의 브리핑이 아직 없습니다.\n"

    md = f"# AI News Radar — 오늘의 브리핑 ({today})\n\n"

    if briefing.get("summary"):
        md += f"> {briefing['summary']}\n\n"

    top = briefing.get("top_articles", [])
    if isinstance(top, list):
        md += "## TOP 뉴스\n\n"
        for i, item in enumerate(top, 1):
            if isinstance(item, dict):
                headline = item.get("headline", item.get("title", ""))
                why = item.get("why_important", item.get("summary", ""))
                md += f"### {i}. {headline}\n"
                if why:
                    md += f"{why}\n"
                md += "\n"

    md += f"\n---\n*Generated by AI News Radar at {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n"
    return md


def export_articles_markdown(articles: list[dict]) -> str:
    """기사 목록을 Markdown으로 내보내기"""
    md = f"# AI News Radar — 뉴스 내보내기 ({today_str()})\n\n"
    md += f"총 {len(articles)}개 기사\n\n---\n\n"

    for a in articles:
        importance = "⭐" * a.get("importance", 0)
        sentiment = SENTIMENTS.get(a.get("sentiment", ""), "")
        category = CATEGORIES.get(a.get("category", ""), "")

        md += f"## {a['title']}\n\n"
        md += f"- **중요도**: {importance}\n"
        md += f"- **감성**: {sentiment}\n"
        md += f"- **카테고리**: {category}\n"
        md += f"- **원문**: [{a['url']}]({a['url']})\n"

        summary = a.get("summary_text", "")
        if summary:
            md += f"\n{summary}\n"

        tags = a.get("tags", [])
        if tags:
            md += f"\n태그: {', '.join(tags)}\n"

        md += "\n---\n\n"

    md += f"*Generated by AI News Radar at {datetime.now().strftime('%Y-%m-%d %H:%M')}*\n"
    return md


# ── PDF 내보내기 ──

def export_briefing_pdf() -> bytes:
    """오늘의 브리핑을 PDF로 내보내기 (bytes 반환)"""
    briefings = safe_read_json(DATA_DIR / "briefings.json", [])
    today = today_str()
    briefing = next((b for b in briefings if b.get("date") == today), None)

    pdf = _KoreanPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # 제목
    pdf.set_font("malgun", "B", 16)
    pdf.cell(0, 12, _safe_text(f"오늘의 AI 브리핑 ({today})"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    if not briefing:
        pdf.set_font("malgun", "", 11)
        pdf.cell(0, 10, "오늘의 브리핑이 아직 없습니다.", new_x="LMARGIN", new_y="NEXT")
        return bytes(pdf.output())

    # 총평
    if briefing.get("summary"):
        pdf.set_font("malgun", "", 11)
        pdf.set_text_color(80, 80, 80)
        pdf.multi_cell(0, 7, _safe_text(briefing["summary"]))
        pdf.set_text_color(0)
        pdf.ln(6)

    # TOP 뉴스
    top = briefing.get("top_articles", [])
    if isinstance(top, list):
        pdf.set_font("malgun", "B", 13)
        pdf.cell(0, 10, "TOP 뉴스", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        for i, item in enumerate(top, 1):
            if isinstance(item, dict):
                headline = item.get("headline", item.get("title", ""))
                why = item.get("why_important", item.get("summary", ""))

                pdf.set_font("malgun", "B", 11)
                pdf.multi_cell(0, 7, _safe_text(f"{i}. {headline}"))

                if why:
                    pdf.set_font("malgun", "", 10)
                    pdf.set_text_color(60, 60, 60)
                    pdf.multi_cell(0, 6, _safe_text(why))
                    pdf.set_text_color(0)

                pdf.ln(4)

    return bytes(pdf.output())


def export_articles_pdf(articles: list[dict]) -> bytes:
    """기사 목록을 PDF로 내보내기 (bytes 반환)"""
    pdf = _KoreanPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # 제목
    pdf.set_font("malgun", "B", 16)
    pdf.cell(0, 12, _safe_text(f"AI 뉴스 내보내기 ({today_str()})"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("malgun", "", 10)
    pdf.cell(0, 8, _safe_text(f"총 {len(articles)}개 기사"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # 구분선
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    for a in articles:
        importance_stars = "*" * a.get("importance", 0)
        sentiment_map = {"positive": "긍정", "negative": "부정", "neutral": "중립"}
        sentiment = sentiment_map.get(a.get("sentiment", ""), "")
        category = CATEGORIES.get(a.get("category", ""), "")

        # 제목
        pdf.set_font("malgun", "B", 12)
        pdf.multi_cell(0, 7, _safe_text(a["title"]))

        # 메타 정보
        pdf.set_font("malgun", "", 9)
        pdf.set_text_color(100, 100, 100)
        meta = f"중요도: {importance_stars}  |  감성: {sentiment}  |  카테고리: {category}"
        pdf.cell(0, 6, _safe_text(meta), new_x="LMARGIN", new_y="NEXT")

        # URL
        pdf.set_text_color(50, 100, 200)
        url_text = a.get("url", "")
        if len(url_text) > 80:
            url_text = url_text[:80] + "..."
        pdf.cell(0, 6, _safe_text(url_text), new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0)

        # 요약
        summary = a.get("summary_text", "")
        if summary:
            pdf.set_font("malgun", "", 10)
            pdf.ln(2)
            pdf.multi_cell(0, 6, _safe_text(summary))

        # 태그
        tags = a.get("tags", [])
        if tags:
            pdf.set_font("malgun", "", 9)
            pdf.set_text_color(80, 80, 80)
            pdf.cell(0, 6, _safe_text(f"태그: {', '.join(tags)}"), new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(0)

        pdf.ln(4)
        pdf.set_draw_color(220, 220, 220)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(4)

    return bytes(pdf.output())
