from db.database import (
    init_db,
    get_articles,
    get_primary_articles,
    upsert_article,
    upsert_articles,
    update_article_fields,
    get_article_by_id,
    search_articles,
    get_unprocessed_articles,
    get_sources,
    upsert_source,
    update_source_crawled,
    get_briefings,
    upsert_briefing,
    get_watchlist,
    add_watchlist_keyword,
    get_active_keywords,
    get_bookmarks,
    add_bookmark,
    remove_bookmark,
    update_bookmark_memo,
    get_bookmark_ids,
    get_alert_log,
    mark_alerted,
    get_weekly_reports,
    upsert_weekly_report,
    get_article_count,
    get_processed_count,
)

__all__ = [
    "init_db", "get_articles", "get_primary_articles",
    "upsert_article", "upsert_articles", "update_article_fields",
    "get_article_by_id", "search_articles", "get_unprocessed_articles",
    "get_sources", "upsert_source", "update_source_crawled",
    "get_briefings", "upsert_briefing",
    "get_watchlist", "add_watchlist_keyword", "get_active_keywords",
    "get_bookmarks", "add_bookmark", "remove_bookmark", "update_bookmark_memo",
    "get_bookmark_ids",
    "get_alert_log", "mark_alerted",
    "get_weekly_reports", "upsert_weekly_report",
    "get_article_count", "get_processed_count",
]
